// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wallet.proto

package msg

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Passwd               string   `protobuf:"bytes,1,opt,name=Passwd,proto3" json:"Passwd,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=Address,proto3" json:"Address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

func (m *Request) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type AddressBlance struct {
	Address              string   `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	UserableAmount       int64    `protobuf:"varint,2,opt,name=UserableAmount,proto3" json:"UserableAmount,omitempty"`
	FrzoneAmount         int64    `protobuf:"varint,3,opt,name=FrzoneAmount,proto3" json:"FrzoneAmount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddressBlance) Reset()         { *m = AddressBlance{} }
func (m *AddressBlance) String() string { return proto.CompactTextString(m) }
func (*AddressBlance) ProtoMessage()    {}
func (*AddressBlance) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{1}
}

func (m *AddressBlance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressBlance.Unmarshal(m, b)
}
func (m *AddressBlance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressBlance.Marshal(b, m, deterministic)
}
func (m *AddressBlance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressBlance.Merge(m, src)
}
func (m *AddressBlance) XXX_Size() int {
	return xxx_messageInfo_AddressBlance.Size(m)
}
func (m *AddressBlance) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressBlance.DiscardUnknown(m)
}

var xxx_messageInfo_AddressBlance proto.InternalMessageInfo

func (m *AddressBlance) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *AddressBlance) GetUserableAmount() int64 {
	if m != nil {
		return m.UserableAmount
	}
	return 0
}

func (m *AddressBlance) GetFrzoneAmount() int64 {
	if m != nil {
		return m.FrzoneAmount
	}
	return 0
}

type BlanceResponse struct {
	Reply                string           `protobuf:"bytes,1,opt,name=Reply,proto3" json:"Reply,omitempty"`
	Blances              []*AddressBlance `protobuf:"bytes,2,rep,name=Blances,proto3" json:"Blances,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *BlanceResponse) Reset()         { *m = BlanceResponse{} }
func (m *BlanceResponse) String() string { return proto.CompactTextString(m) }
func (*BlanceResponse) ProtoMessage()    {}
func (*BlanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{2}
}

func (m *BlanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlanceResponse.Unmarshal(m, b)
}
func (m *BlanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlanceResponse.Marshal(b, m, deterministic)
}
func (m *BlanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlanceResponse.Merge(m, src)
}
func (m *BlanceResponse) XXX_Size() int {
	return xxx_messageInfo_BlanceResponse.Size(m)
}
func (m *BlanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BlanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BlanceResponse proto.InternalMessageInfo

func (m *BlanceResponse) GetReply() string {
	if m != nil {
		return m.Reply
	}
	return ""
}

func (m *BlanceResponse) GetBlances() []*AddressBlance {
	if m != nil {
		return m.Blances
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "msg.Request")
	proto.RegisterType((*AddressBlance)(nil), "msg.AddressBlance")
	proto.RegisterType((*BlanceResponse)(nil), "msg.BlanceResponse")
}

func init() { proto.RegisterFile("wallet.proto", fileDescriptor_b88fd140af4deb6f) }

var fileDescriptor_b88fd140af4deb6f = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x09, 0x16, 0x89, 0x7a, 0x84, 0x0e, 0x07, 0x42, 0x11, 0x13, 0xf2, 0x80, 0x3a, 0xa0,
	0x08, 0x95, 0x0d, 0xa6, 0x32, 0xc0, 0x8a, 0x2c, 0x10, 0xb3, 0x4b, 0x4e, 0x5d, 0x1c, 0x3b, 0xf8,
	0x1c, 0x55, 0xf0, 0xeb, 0x11, 0x8e, 0x23, 0xe1, 0x6e, 0x7e, 0xe7, 0xcf, 0x7e, 0xef, 0x1e, 0xd4,
	0x7b, 0x6d, 0x0c, 0x85, 0x76, 0xf0, 0x2e, 0x38, 0x14, 0x3d, 0xef, 0xe4, 0x23, 0x54, 0x8a, 0xbe,
	0x46, 0xe2, 0x80, 0x97, 0x50, 0xbe, 0x6a, 0xe6, 0x7d, 0xd7, 0x14, 0xd7, 0xc5, 0x6a, 0xa1, 0x92,
	0xc2, 0x06, 0xaa, 0x4d, 0xd7, 0x79, 0x62, 0x6e, 0x8e, 0xe3, 0xc5, 0x2c, 0xe5, 0x08, 0x67, 0xe9,
	0xf8, 0x64, 0xb4, 0xfd, 0xa4, 0xff, 0x68, 0x91, 0xa1, 0x78, 0x03, 0xcb, 0x77, 0x26, 0xaf, 0xb7,
	0x86, 0x36, 0xbd, 0x1b, 0x6d, 0x88, 0x7f, 0x09, 0x75, 0x30, 0x45, 0x09, 0xf5, 0xb3, 0xff, 0x71,
	0x76, 0xa6, 0x44, 0xa4, 0xb2, 0x99, 0x7c, 0x83, 0xe5, 0xe4, 0xa7, 0x88, 0x07, 0x67, 0x99, 0xf0,
	0x02, 0x4e, 0x14, 0x0d, 0xe6, 0x3b, 0xb9, 0x4e, 0x02, 0x6f, 0xa1, 0x9a, 0xb8, 0xbf, 0xe0, 0x62,
	0x75, 0xba, 0xc6, 0xb6, 0xe7, 0x5d, 0x9b, 0x45, 0x56, 0x33, 0xb2, 0x7e, 0x80, 0xf2, 0x23, 0xd6,
	0x83, 0x77, 0xb0, 0x78, 0xa1, 0x90, 0x56, 0xaa, 0xe3, 0x9b, 0xd4, 0xd1, 0xd5, 0x79, 0x54, 0xb9,
	0xbb, 0x3c, 0xda, 0x96, 0xb1, 0xd1, 0xfb, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x11, 0x24, 0xfd,
	0xbf, 0x61, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WalletClient is the client API for Wallet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WalletClient interface {
	GetBlance(ctx context.Context, in *Request, opts ...grpc.CallOption) (*BlanceResponse, error)
}

type walletClient struct {
	cc *grpc.ClientConn
}

func NewWalletClient(cc *grpc.ClientConn) WalletClient {
	return &walletClient{cc}
}

func (c *walletClient) GetBlance(ctx context.Context, in *Request, opts ...grpc.CallOption) (*BlanceResponse, error) {
	out := new(BlanceResponse)
	err := c.cc.Invoke(ctx, "/msg.Wallet/GetBlance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletServer is the server API for Wallet service.
type WalletServer interface {
	GetBlance(context.Context, *Request) (*BlanceResponse, error)
}

func RegisterWalletServer(s *grpc.Server, srv WalletServer) {
	s.RegisterService(&_Wallet_serviceDesc, srv)
}

func _Wallet_GetBlance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).GetBlance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/msg.Wallet/GetBlance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).GetBlance(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Wallet_serviceDesc = grpc.ServiceDesc{
	ServiceName: "msg.Wallet",
	HandlerType: (*WalletServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBlance",
			Handler:    _Wallet_GetBlance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wallet.proto",
}
